/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedBindBankRouteImport } from './routes/_authenticated/bind-bank'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedCustomerServiceRouteImport } from './routes/_authenticated/customer-service'
import { Route as AuthenticatedGiftCodeRouteImport } from './routes/_authenticated/gift-code'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMineRouteImport } from './routes/_authenticated/mine'
import { Route as AuthenticatedMyProductsRouteImport } from './routes/_authenticated/my-products'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedRechargeRouteImport } from './routes/_authenticated/recharge'
import { Route as AuthenticatedRechargeProblemRouteImport } from './routes/_authenticated/recharge-problem'
import { Route as AuthenticatedRecordsRouteImport } from './routes/_authenticated/records'
import { Route as AuthenticatedRegulationRouteImport } from './routes/_authenticated/regulation'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTeamRecordsRouteImport } from './routes/_authenticated/team-records'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBindBankRoute = AuthenticatedBindBankRouteImport.update({
  id: '/bind-bank',
  path: '/bind-bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomerServiceRoute =
  AuthenticatedCustomerServiceRouteImport.update({
    id: '/customer-service',
    path: '/customer-service',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGiftCodeRoute = AuthenticatedGiftCodeRouteImport.update({
  id: '/gift-code',
  path: '/gift-code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMineRoute = AuthenticatedMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyProductsRoute = AuthenticatedMyProductsRouteImport.update({
  id: '/my-products',
  path: '/my-products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeRoute = AuthenticatedRechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRechargeProblemRoute =
  AuthenticatedRechargeProblemRouteImport.update({
    id: '/recharge-problem',
    path: '/recharge-problem',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecordsRoute = AuthenticatedRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegulationRoute = AuthenticatedRegulationRouteImport.update({
  id: '/regulation',
  path: '/regulation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRecordsRoute =
  AuthenticatedTeamRecordsRouteImport.update({
    id: '/team-records',
    path: '/team-records',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AuthenticatedAboutRoute
  '/bind-bank': typeof AuthenticatedBindBankRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/gift-code': typeof AuthenticatedGiftCodeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mine': typeof AuthenticatedMineRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/recharge-problem': typeof AuthenticatedRechargeProblemRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/regulation': typeof AuthenticatedRegulationRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-records': typeof AuthenticatedTeamRecordsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/about': typeof AuthenticatedAboutRoute
  '/bind-bank': typeof AuthenticatedBindBankRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/gift-code': typeof AuthenticatedGiftCodeRoute
  '/home': typeof AuthenticatedHomeRoute
  '/mine': typeof AuthenticatedMineRoute
  '/my-products': typeof AuthenticatedMyProductsRoute
  '/products': typeof AuthenticatedProductsRoute
  '/recharge': typeof AuthenticatedRechargeRoute
  '/recharge-problem': typeof AuthenticatedRechargeProblemRoute
  '/records': typeof AuthenticatedRecordsRoute
  '/regulation': typeof AuthenticatedRegulationRoute
  '/team': typeof AuthenticatedTeamRoute
  '/team-records': typeof AuthenticatedTeamRecordsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/bind-bank': typeof AuthenticatedBindBankRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/customer-service': typeof AuthenticatedCustomerServiceRoute
  '/_authenticated/gift-code': typeof AuthenticatedGiftCodeRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/mine': typeof AuthenticatedMineRoute
  '/_authenticated/my-products': typeof AuthenticatedMyProductsRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/recharge': typeof AuthenticatedRechargeRoute
  '/_authenticated/recharge-problem': typeof AuthenticatedRechargeProblemRoute
  '/_authenticated/records': typeof AuthenticatedRecordsRoute
  '/_authenticated/regulation': typeof AuthenticatedRegulationRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/team-records': typeof AuthenticatedTeamRecordsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/bind-bank'
    | '/change-password'
    | '/checkin'
    | '/customer-service'
    | '/gift-code'
    | '/home'
    | '/mine'
    | '/my-products'
    | '/products'
    | '/recharge'
    | '/recharge-problem'
    | '/records'
    | '/regulation'
    | '/team'
    | '/team-records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/about'
    | '/bind-bank'
    | '/change-password'
    | '/checkin'
    | '/customer-service'
    | '/gift-code'
    | '/home'
    | '/mine'
    | '/my-products'
    | '/products'
    | '/recharge'
    | '/recharge-problem'
    | '/records'
    | '/regulation'
    | '/team'
    | '/team-records'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/about'
    | '/_authenticated/bind-bank'
    | '/_authenticated/change-password'
    | '/_authenticated/checkin'
    | '/_authenticated/customer-service'
    | '/_authenticated/gift-code'
    | '/_authenticated/home'
    | '/_authenticated/mine'
    | '/_authenticated/my-products'
    | '/_authenticated/products'
    | '/_authenticated/recharge'
    | '/_authenticated/recharge-problem'
    | '/_authenticated/records'
    | '/_authenticated/regulation'
    | '/_authenticated/team'
    | '/_authenticated/team-records'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bind-bank': {
      id: '/_authenticated/bind-bank'
      path: '/bind-bank'
      fullPath: '/bind-bank'
      preLoaderRoute: typeof AuthenticatedBindBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customer-service': {
      id: '/_authenticated/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof AuthenticatedCustomerServiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gift-code': {
      id: '/_authenticated/gift-code'
      path: '/gift-code'
      fullPath: '/gift-code'
      preLoaderRoute: typeof AuthenticatedGiftCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mine': {
      id: '/_authenticated/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof AuthenticatedMineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-products': {
      id: '/_authenticated/my-products'
      path: '/my-products'
      fullPath: '/my-products'
      preLoaderRoute: typeof AuthenticatedMyProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge': {
      id: '/_authenticated/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof AuthenticatedRechargeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recharge-problem': {
      id: '/_authenticated/recharge-problem'
      path: '/recharge-problem'
      fullPath: '/recharge-problem'
      preLoaderRoute: typeof AuthenticatedRechargeProblemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/records': {
      id: '/_authenticated/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AuthenticatedRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/regulation': {
      id: '/_authenticated/regulation'
      path: '/regulation'
      fullPath: '/regulation'
      preLoaderRoute: typeof AuthenticatedRegulationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team-records': {
      id: '/_authenticated/team-records'
      path: '/team-records'
      fullPath: '/team-records'
      preLoaderRoute: typeof AuthenticatedTeamRecordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedBindBankRoute: typeof AuthenticatedBindBankRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedCustomerServiceRoute: typeof AuthenticatedCustomerServiceRoute
  AuthenticatedGiftCodeRoute: typeof AuthenticatedGiftCodeRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMineRoute: typeof AuthenticatedMineRoute
  AuthenticatedMyProductsRoute: typeof AuthenticatedMyProductsRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedRechargeRoute: typeof AuthenticatedRechargeRoute
  AuthenticatedRechargeProblemRoute: typeof AuthenticatedRechargeProblemRoute
  AuthenticatedRecordsRoute: typeof AuthenticatedRecordsRoute
  AuthenticatedRegulationRoute: typeof AuthenticatedRegulationRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTeamRecordsRoute: typeof AuthenticatedTeamRecordsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedBindBankRoute: AuthenticatedBindBankRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedCustomerServiceRoute: AuthenticatedCustomerServiceRoute,
  AuthenticatedGiftCodeRoute: AuthenticatedGiftCodeRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMineRoute: AuthenticatedMineRoute,
  AuthenticatedMyProductsRoute: AuthenticatedMyProductsRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedRechargeRoute: AuthenticatedRechargeRoute,
  AuthenticatedRechargeProblemRoute: AuthenticatedRechargeProblemRoute,
  AuthenticatedRecordsRoute: AuthenticatedRecordsRoute,
  AuthenticatedRegulationRoute: AuthenticatedRegulationRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTeamRecordsRoute: AuthenticatedTeamRecordsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
